[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/o-que-e-seo/"
  to = "/"
  status = 301
  force = true

[functions]
external_node_modules = ["jsdom", "@mozilla/readability", "rss-parser", "openai"]
