[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/o-que-e-seo/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/9-ferramentas-para-criar-google-web-stories/"
  to = "/melhores-ferramentas-para-criar-google-web-stories/"
  status = 301
  force = true

[[redirects]]
  from = "/resumo-drops-seo-12-11-18-11/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/resumo-drops-seo-19-11-25-11/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/search-gpt-tudo-o-que-voce-precisa-saber-para-ranquear-no-buscador-da-openai/"
  to = "/o-que-e-searchgpt-tudo-para-ranquear-no-buscador-da-openai/"
  status = 301
  force = true

[[redirects]]
  from= "/webstory/:slug/"
  to="https://admin.ottovarga.com.br/webstory/:slug/"
  status=200
  force=true
  headers = {X-From = "Netlify"}

[functions]
  external_node_modules = ["jsdom", "@mozilla/readability", "rss-parser", "openai"]
